### ISSUE TITLE
Rename theme submodule

### ISSUE THREAD

**Issue by akirarorschach** [The-Zombie-Fridge-Journal/zfjournal_source#4]
**DESCRIPTION** 
The website theme submodule needs to be renamed from `hugo-theme-novela` to `website_theme`. This has already been done to the [forked repository](https://github.com/The-Zombie-Fridge-Journal/website_theme). However, the submodule in `zfjournal_source` still remains named as `hugo-theme-novela`. 

**OBJECTIVE** 
rename submodule in `zfjournal_source` to `website_theme` 

**POSSIBLE SOLUTIONS** 
The submodule has to be deleted and then readded with the correct name. 

**REFERENCES**
commits with the progress so far: 
https://github.com/The-Zombie-Fridge-Journal/zfjournal_source/commit/d86ebee5d271c1780fd014487b9d436a1ae79871
https://github.com/The-Zombie-Fridge-Journal/zfjournal_source/commit/8bfa0e3052905e723ee3378d13b3396f7e988de6
https://github.com/The-Zombie-Fridge-Journal/zfjournal_source/commit/3622bd49066b655ab83490238a6ec40330dc2e93
https://github.com/The-Zombie-Fridge-Journal/zfjournal_source/commit/6310e63b46f38ee04880ae8bde6e5f08fd367669

**Comment by Dodesimo** [comment]
**POSTMORTEM REPORT**

The problem was solved using the following steps:

1. Remove the `hugo-theme-novela` submodule using `git submodule deinit [path of the theme]`
2. Add the renamed `website_theme` submodule using `git submodule add [link of submodule]`
3. Edit the `.gitsubmodules` file to remove the `hugo-theme-novela` entry. 

Because the website built successfully after the issue patch was committed, I will close this issue.
